services:
  sap-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sap-backend-img:latest
    container_name: sap-backend
    ports:
      - "8081:8082"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - network-battilana
    restart: unless-stopped
networks:
  network-battilana:
    external: true